query AllPosts($first: IntType = 10, $skip: IntType = 0, $locale: SiteLocale) {
  allPosts(first: $first, skip: $skip, locale: $locale) {
    id
    slug
    title
    createdAt
    updatedAt
  }
  _allPostsMeta {
    count
  }
}

query Post($slug: String!, $locale: SiteLocale) {
  post(filter: { slug: { eq: $slug } }, locale: $locale) {
    id
    title
    slug
    image {
      ...ImageFragment
    }
    content(markdown: false)
    createdAt
    updatedAt
  }
}
