query AllPosts($first: IntType = 10, $skip: IntType = 0, $locale: SiteLocale) {
  allPosts(first: $first, skip: $skip, locale: $locale) {
    ...PostFragment
  }
  _allPostsMeta {
    count
  }
}

query Post($slug: String!, $locale: SiteLocale) {
  post(locale: $locale, filter: { slug: { eq: $slug } }) {
    ...PostFragment
  }
}
fragment PostFragment on PostRecord {
  id
  title
  slug
  slugs: _allSlugLocales {
    locale
    value
  }
  image {
    ...ImageFragment
  }
  content(markdown: false)
  structuredContent {
    blocks {
      ... on PageRecord {
        id
        intro
        title
      }
    }
    links
    value
  }
  createdAt
  updatedAt
}
