query AllProjects($first: IntType = 500, $skip: IntType) {
	allProjects(first: $first, skip: $skip, orderBy: title_ASC) {
		...ProjectFragment
	}
	_allProjectsMeta {
		count
	}
}

query Project($slug: String) {
	project(filter: { slug: { eq: $slug } }) {
		...ProjectFragment
	}
}

query ProjectById($id: ItemId!) {
	project(filter: { id: { eq: $id } }) {
		...ProjectFragment
	}
}

fragment ProjectFragment on ProjectRecord {
	id
	title
	caption(markdown: false)
	captionStyle
	category
	url
	slug
	color {
		...ColorFragment
	}
	background {
		...ColorFragment
	}
	thumbnail {
		...ImageThumbnailFragment
	}
	_updatedAt
}
